
Time: 21 Nov 2018 21:49:14:
Traceback (most recent call last):
  File "runexperiment.py", line 95, in <module>
    cont.startExperiment(closeWindowOnExit)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 90, in startExperiment
    pyglet.app.run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 264, in run
    EventLoop().run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 63, in run
    self._timer_func(0, 0, timer, 0)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 84, in _timer_func
    sleep_time = self.idle()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 187, in idle
    dt = clock.tick(True)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 700, in tick
    return _default.tick(poll)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 303, in tick
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tobii\tobii.py", line 374, in update
    self.updateGazeHeadPos()
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tobii\tobii.py", line 414, in updateGazeHeadPos
    self.gazeHeadPos[i] = self.gazeHeadBuffer[i].getAverage()
IndexError: list assignment index out of range

Time: 21 Nov 2018 22:06:51:
Traceback (most recent call last):
  File "runexperiment.py", line 95, in <module>
    cont.startExperiment(closeWindowOnExit)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 90, in startExperiment
    pyglet.app.run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 264, in run
    EventLoop().run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 63, in run
    self._timer_func(0, 0, timer, 0)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 84, in _timer_func
    sleep_time = self.idle()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 187, in idle
    dt = clock.tick(True)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 700, in tick
    return _default.tick(poll)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 303, in tick
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tobii\tobii.py", line 386, in update
    self.gazeHeadPos[0],
IndexError: list index out of range

Time: 21 Nov 2018 22:07:05:
Traceback (most recent call last):
  File "runexperiment.py", line 95, in <module>
    cont.startExperiment(closeWindowOnExit)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 90, in startExperiment
    pyglet.app.run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 264, in run
    EventLoop().run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 63, in run
    self._timer_func(0, 0, timer, 0)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 84, in _timer_func
    sleep_time = self.idle()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 187, in idle
    dt = clock.tick(True)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 700, in tick
    return _default.tick(poll)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 303, in tick
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tobii\tobii.py", line 386, in update
    self.gazeHeadPos[0],
IndexError: list index out of range

Time: 21 Nov 2018 22:07:56:
Traceback (most recent call last):
  File "runexperiment.py", line 95, in <module>
    cont.startExperiment(closeWindowOnExit)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 90, in startExperiment
    pyglet.app.run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 264, in run
    EventLoop().run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 63, in run
    self._timer_func(0, 0, timer, 0)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 84, in _timer_func
    sleep_time = self.idle()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 187, in idle
    dt = clock.tick(True)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 700, in tick
    return _default.tick(poll)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 303, in tick
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 191, in _startNextEvent
    self._startRoutine(rName, fObj.attribs['condition'])
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 244, in _startRoutine
    compObj.start(duration=duration, configName=configName)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\billboard\billboardImage.py", line 229, in start
    DrawableModule.start(self, dt, duration, configName)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\abstract\AbstractClasses.py", line 109, in start
    raise KeyError('Config "%s" is not known.' % configName)
KeyError: 'Config "pic1" is not known.'

Time: 21 Nov 2018 22:08:30:
Traceback (most recent call last):
  File "runexperiment.py", line 95, in <module>
    cont.startExperiment(closeWindowOnExit)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 90, in startExperiment
    pyglet.app.run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 264, in run
    EventLoop().run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 63, in run
    self._timer_func(0, 0, timer, 0)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 84, in _timer_func
    sleep_time = self.idle()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 187, in idle
    dt = clock.tick(True)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 700, in tick
    return _default.tick(poll)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 303, in tick
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tobii\tobii.py", line 386, in update
    self.gazeHeadPos[0],
IndexError: list index out of range

Time: 21 Nov 2018 22:09:08:
Traceback (most recent call last):
  File "runexperiment.py", line 95, in <module>
    cont.startExperiment(closeWindowOnExit)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 90, in startExperiment
    pyglet.app.run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 264, in run
    EventLoop().run()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 63, in run
    self._timer_func(0, 0, timer, 0)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\win32.py", line 84, in _timer_func
    sleep_time = self.idle()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\app\__init__.py", line 187, in idle
    dt = clock.tick(True)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 700, in tick
    return _default.tick(poll)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\pyglet\clock.py", line 303, in tick
    item.func(ts - item.last_ts, *item.args, **item.kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tobii\tobii.py", line 386, in update
    self.gazeHeadPos[0],
IndexError: list index out of range

Time: 21 Nov 2018 22:24:42:
Traceback (most recent call last):
  File "runexperiment.py", line 78, in <module>
    cont.loadExperiment(arg)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 77, in loadExperiment
    self._loadExpInstance(filename)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 302, in _loadExpInstance
    self._loadExpOverview(os.path.join(filepath, expNode.attrib['fileName']))
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 335, in _loadExpOverview
    self._loadComponents(tree)      # Load Components
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 478, in _loadComponents
    self._importModule(comp)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 557, in _importModule
    curComp = mymodule.ModuleMain(self, initConfig=comp.initParams, runConfigs=comp.params)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\scene\pythonScript.py", line 72, in __init__
    self.updatecode[confName] = compile( code, '<string>', 'exec' )
  File "<string>", line 1
     $EXPYVRROOT$/experiments/CardioVisualExp/script/updateImageOneIsSync.py
     ^
 SyntaxError: invalid syntax

Time: 21 Nov 2018 22:26:30:
Traceback (most recent call last):
  File "runexperiment.py", line 78, in <module>
    cont.loadExperiment(arg)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 77, in loadExperiment
    self._loadExpInstance(filename)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 302, in _loadExpInstance
    self._loadExpOverview(os.path.join(filepath, expNode.attrib['fileName']))
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 335, in _loadExpOverview
    self._loadComponents(tree)      # Load Components
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 478, in _loadComponents
    self._importModule(comp)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 557, in _importModule
    curComp = mymodule.ModuleMain(self, initConfig=comp.initParams, runConfigs=comp.params)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tracker\ArduinoECGModule.py", line 305, in __init__
    self.sensor = Arduino(port=self.initConf['port'], baudrate=115200)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tracker\ArduinoECGModule.py", line 34, in __init__
    serial.Serial.__init__(self, *args, **kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\serial\serialwin32.py", line 30, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\serial\serialutil.py", line 260, in __init__
    self.open()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\serial\serialwin32.py", line 56, in open
    raise SerialException("could not open port %s: %s" % (self.portstr, ctypes.WinError()))
SerialException: could not open port COM3: [Error 5] Access is denied.

Time: 21 Nov 2018 22:26:59:
Traceback (most recent call last):
  File "runexperiment.py", line 78, in <module>
    cont.loadExperiment(arg)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 77, in loadExperiment
    self._loadExpInstance(filename)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 302, in _loadExpInstance
    self._loadExpOverview(os.path.join(filepath, expNode.attrib['fileName']))
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 335, in _loadExpOverview
    self._loadComponents(tree)      # Load Components
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 478, in _loadComponents
    self._importModule(comp)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 557, in _importModule
    curComp = mymodule.ModuleMain(self, initConfig=comp.initParams, runConfigs=comp.params)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\scene\pythonScript.py", line 72, in __init__
    self.updatecode[confName] = compile( code, '<string>', 'exec' )
  File "<string>", line 1
     $EXPYVRROOT$/experiments/CardioVisualExp/script/updateOneIsSync.py
     ^
 SyntaxError: invalid syntax

Time: 21 Nov 2018 22:28:00:
Traceback (most recent call last):
  File "runexperiment.py", line 78, in <module>
    cont.loadExperiment(arg)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 77, in loadExperiment
    self._loadExpInstance(filename)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 302, in _loadExpInstance
    self._loadExpOverview(os.path.join(filepath, expNode.attrib['fileName']))
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 335, in _loadExpOverview
    self._loadComponents(tree)      # Load Components
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 478, in _loadComponents
    self._importModule(comp)
  File "C:\Users\pfeif\Repos\CardioVisual\expyvr\src\controller\maincontrol.py", line 557, in _importModule
    curComp = mymodule.ModuleMain(self, initConfig=comp.initParams, runConfigs=comp.params)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tracker\ArduinoECGModule.py", line 305, in __init__
    self.sensor = Arduino(port=self.initConf['port'], baudrate=115200)
  File "C:\Users\pfeif\Repos\CardioVisual\lncocomponents\tracker\ArduinoECGModule.py", line 34, in __init__
    serial.Serial.__init__(self, *args, **kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\serial\serialwin32.py", line 30, in __init__
    SerialBase.__init__(self, *args, **kwargs)
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\serial\serialutil.py", line 260, in __init__
    self.open()
  File "C:\Users\pfeif\Repos\CardioVisual\python26\lib\site-packages\serial\serialwin32.py", line 56, in open
    raise SerialException("could not open port %s: %s" % (self.portstr, ctypes.WinError()))
SerialException: could not open port COM3: [Error 5] Access is denied.
